name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install MinGW
      run: |
        choco install mingw --version=8.1.0 -y  # Install MinGW via Chocolatey
        echo "PATH=$(choco info mingw --output json | jq -r .installed | tr -d '\n' | sed 's/\\/\//g')" >> $GITHUB_ENV  # Update PATH

    - name: Configure
      run: cmake -S . -B build -G "MinGW Makefiles"  # Use MinGW Makefiles for g++

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build

    - name: Package
      run: cpack --config build/CPackConfig.cmake
